version: 0.0
os: "linux"
files:
  - source: "/"
    destination: "/home/ubuntu/flights_release/"
permissions:
  - object: /home/ubuntu/flights/
    pattern: "**"
    owner: ubuntu
    # group: nginx
    mode: 755
    type:
      - file
hooks:
    BeforeInstall:
        - location: scripts/beforeInstall.bash
    AfterInstall:
        - location: scripts/afterInstall.bash
    ValidateService:
        - location: scripts/restart.bash
