aws:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  region: 'eu-central-1'
  secret_access_key:  <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  receive_message:
    attribute_names:
      - ApproximateReceiveCount
      - SentTimestamp
  logfile: /home/ec2-user/flights/log/shoryuken.log
  pidfile: /home/ec2-user/flights/log/shoryuken.pid
concurrency: 3
delay: 0
timeout: 100
wait_time_second: 6
queues:
  - production_priceupdate
